### PR TITLE
Use the POST data to try an autologin

### PR DESCRIPTION
**Pull request by himmelbuerger**
If you find this useful I could clean up a little (if there is a better place or coding guidelines or whatever should be improved). Otherwise I would leave it like this, because for me this works. 
I'm now able to use the androidApp with the mobile version of Kimai with autologin

### CODE REVIEW

**Comment by simonschaufi** [comment]
Thank you very much for your first pull request! I did some slight code changes but before merging I will think about this implementation again if this is really the best solution as it's quite "hacky".

**Comment by simonschaufi** [comment]
@kevinpapst what do you think about that? Prefilling the form and then immitating the form submit is not the best solution imho.

**Comment by kevinpapst** [comment]
> This tool was NEVER meant to be used in production, it is a demonstration of the remote API.

I don't like the choosen approach - I would have prefered a JS way. 
But actually I don't care - if it works I don't mind merging.

**Comment by kevinpapst** [comment]
If you wonder what the heck is that after almost 2 years: I am cleaning up repositories and stuff

**Pull request merged**
